sap.ui.require.preload({
	"web/navigation/Component.js": "sap.ui.define([\"sap/ui/core/UIComponent\",\"sap/ui/Device\",\"navigation/model/models\"],function(n,e,t){\"use strict\";return n.extend(\"navigation.Component\",{metadata:{manifest:\"json\"},init:function(){n.prototype.init.apply(this,arguments),this.components={},this.setModel(t.createDeviceModel(),\"device\")},getComponent:function(n,e){return new Promise((t,o)=>{this.components[n]?t(this.components[n]):(this.components[n]=new Promise((t,o)=>{t(sap.ui.component({name:n,manifest:e,componentData:{}}))}),t(this.components[n]))})}})});",
	"web/navigation/controller/App.controller.js": "sap.ui.define([\"sap/ui/core/mvc/Controller\",\"navigation/model/formatter\"],function(t,n){\"use strict\";return t.extend(\"navigation.controller.App\",{formatter:n,onInit:function(){var t=this;new Promise((t,n)=>{t(this.getOwnerComponent().getComponent(\"sap.gantt.sample.BasicGanttChart\",!0))}).then(function(n){console.log(n);var o=n.getAggregation(\"rootControl\");t.byId(\"navPage\").addContent(o)})}})});",
	"web/navigation/model/formatter.js": "sap.ui.define([],function(){\"use strict\";return{}});",
	"web/navigation/model/models.js": "sap.ui.define([\"sap/ui/model/json/JSONModel\",\"sap/ui/Device\"],function(e,n){\"use strict\";return{createDeviceModel:function(){var i=new e(n);return i.setDefaultBindingMode(\"OneWay\"),i}}});",
	"web/navigation/test/integration/AllJourneys.js": "jQuery.sap.require(\"sap.ui.qunit.qunit-css\"),jQuery.sap.require(\"sap.ui.thirdparty.qunit\"),jQuery.sap.require(\"sap.ui.qunit.qunit-junit\"),QUnit.config.autostart=!1,sap.ui.require([\"sap/ui/test/Opa5\",\"navigation/test/integration/pages/Common\",\"sap/ui/test/opaQunit\",\"navigation/test/integration/pages/App\"],function(i,t){\"use strict\";i.extendConfig({arrangements:new t,viewNamespace:\"navigation.view.\"}),sap.ui.require([\"navigation/test/integration/navigationJourney\"],function(){QUnit.start()})});",
	"web/navigation/test/integration/navigationJourney.js": "sap.ui.define([\"sap/ui/test/opaQunit\"],function(e){\"use strict\";QUnit.module(\"Navigation Journey\"),e(\"Should see the initial page of the app\",function(e,i,p){e.iStartTheApp(),i.onTheAppPage.iLookAtTheScreen(),p.onTheAppPage.iShouldSeeTheApp().and.iTeardownMyAppFrame()})});",
	"web/navigation/test/integration/pages/App.js": "sap.ui.define([\"sap/ui/test/Opa5\",\"navigation/test/integration/pages/Common\"],function(e,s){\"use strict\";e.createPageObjects({onTheAppPage:{baseClass:s,actions:{},assertions:{iShouldSeeTheApp:function(){return this.waitFor({id:\"page\",viewName:\"App\",success:function(){e.assert.ok(!0,\"The App view is displayed\")},errorMessage:\"Did not find the App view\"})}}}})});",
	"web/navigation/test/integration/pages/Common.js": "sap.ui.define([\"sap/ui/test/Opa5\"],function(t){\"use strict\";return t.extend(\"navigation.test.integration.pages.Common\",{iStartTheApp:function(t){var e,n,i;t=t||{},this.iStartMyAppInAFrame((e=t.hash,i=jQuery.sap.getResourcePath(\"navigation/app\",\".html\"),e=e||\"\",i+(n=n?\"?\"+n:\"\")+(e=e?\"#\"+(0===e.indexOf(\"/\")?e.substring(1):e):\"\")))},iLookAtTheScreen:function(){return this}})});",
	"web/navigation/test/unit/allTests.js": "sap.ui.define([\"test/unit/model/formatter\",\"test/unit/controller/App.controller\"],function(){\"use strict\"});",
	"web/navigation/test/unit/controller/App.controller.js": "sap.ui.define([\"navigation/controller/App.controller\"],function(t){\"use strict\";QUnit.module(\"App Controller\"),QUnit.test(\"I should test the app controller\",function(n){var o=new t;o.onInit(),n.ok(o)})});",
	"web/navigation/test/unit/model/formatter.js": "sap.ui.define([\"navigation/model/formatter\"],function(){\"use strict\";QUnit.module(\"Formatters\"),QUnit.test(\"I should test my formatters\",function(t){t.ok(!0)})});",
	"web/navigation/view/App.view.xml": "<mvc:View\n\tcontrollerName=\"navigation.controller.App\"\n\txmlns:mvc=\"sap.ui.core.mvc\"\n\tdisplayBlock=\"true\"\n\txmlns=\"sap.m\"><App><pages><Page\n\t\t\t\tid=\"navPage\"\n\t\t\t\ttitle=\"{i18n>title}\"><content></content></Page></pages></App></mvc:View>",
	"web/navigation/i18n/i18n.properties": "title=Navigation\nappTitle=Navigation\nappDescription=Component to handle navigation within the application"
}, "web/navigation/Component-preload");